[snowflake]
user = 'VARAD_POC'
password = 'Sr71@blackbird'
account = 'blazeclanpartner.sg.ap-southeast-1.aws'
database = 'CODE_REPO'
role = 'SYSADMIN'
warehouse = 'POC_WH'
schema = 'DATA_ACCELERATOR_SCHEMA'